// Built-in guides: the generated main walkthrough plus the weapon build guides (generated by our planner offline).
import { curatedGuides } from "@/lib/guides/data";
import { fromLegacyGuide } from "./legacy";
import { mainWalkthrough } from "./main";
import type { Guide } from "./types";

export const weaponGuides: Guide[] = curatedGuides.map((g) => fromLegacyGuide(g));
export const builtinGuides: Guide[] = [mainWalkthrough, ...weaponGuides];
export const builtinGuideById = new Map(builtinGuides.map((g) => [g.id, g]));

/** Built-in guides followed by the profile's own guides. */
export const allGuides = (own: Guide[]): Guide[] => [...builtinGuides, ...own];

export function findGuide(id: string, own: Guide[]): Guide | undefined {
  return builtinGuideById.get(id) ?? own.find((g) => g.id === id);
}
