// Built-in guides: the generated main walkthrough plus the weapon build guides (generated by our planner offline,
// see scripts/planner/curated.ts).
import guidesJson from "@/data/guides.json";
import { z } from "zod";
import { mainWalkthrough } from "./main";
import { guide, type Guide } from "./types";

export const weaponGuides: Guide[] = z.array(guide).parse(guidesJson);
export const builtinGuides: Guide[] = [mainWalkthrough, ...weaponGuides];
export const builtinGuideById = new Map(builtinGuides.map((g) => [g.id, g]));

/** Built-in guides followed by the profile's own guides. */
export const allGuides = (own: Guide[]): Guide[] => [...builtinGuides, ...own];

export function findGuide(id: string, own: Guide[]): Guide | undefined {
  return builtinGuideById.get(id) ?? own.find((g) => g.id === id);
}
