// Compares the two guides' extracted data and writes the differences to src/data/INCONSISTENCIES.md.
// Run after the extractors: node scripts/extract/crosscheck.ts
import { readFileSync, writeFileSync } from "node:fs";

const read = <T>(f: string): T => JSON.parse(readFileSync(`src/data/${f}`, "utf8"));

interface Weapon {
  id: string;
  name: string;
  baseAbs: number;
  spPerLevel: number;
  combo?: string;
  abilities: string[];
  buildsUpTo: string[];
  requiresKills: string[];
  baseStats: Record<string, number>;
  maxStats: Record<string, number>;
  maxDu: number;
}
interface WtWeapon {
  id: string;
  name: string;
  combos?: number;
  sp: number;
  baseAbs: number;
  abilities: string[];
  buildsUpTo: string[];
  minStats: number[];
  maxStats: number[];
  enemies: string[];
}
const faq = read<{
  weapons: Weapon[];
  shops: { chapter: number; shop: string; weaponId: string; price: number }[];
  invented: { weaponId: string; ideas: string[][]; materials: { name: string; qty: number }[] }[];
  events: { weaponId: string; how: string }[];
  killEnemies: { name: string; chapter?: number }[];
}>("weapons.json");
const wt = read<WtWeapon[]>("weapons-walkthrough.json");
const shops =
  read<{ name: string; items: { name: string; price?: number; chapter?: number }[] }[]>(
    "shops.json",
  );
const inventions = read<
  {
    name: string;
    chapter: number;
    ideas: { name: string }[];
    components: { name: string; qty: number }[];
  }[]
>("inventions.json");
const georama = read<{ areas: { name: string; reward?: string }[] }>("georama.json");
const sections =
  read<{ id: string; chapterId: string; title: string; enemies: { name: string }[] }[]>(
    "sections.json",
  );

const byId = new Map(faq.weapons.map((w) => [w.id, w]));
const nameOf = (id: string) => byId.get(id)?.name ?? id;
const out: string[] = [];
const h = (s: string) => out.push("", s, "");
const bullet = (s: string) => out.push(`- ${s}`);
const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

function distance(a: string, b: string) {
  const d = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)]);
  for (let j = 1; j <= b.length; j++) d[0][j] = j;
  for (let i = 1; i <= a.length; i++)
    for (let j = 1; j <= b.length; j++)
      d[i][j] = Math.min(
        d[i - 1][j] + 1,
        d[i][j - 1] + 1,
        d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1),
      );
  return d[a.length][b.length];
}

out.push("# Differences between the two guides", "");
out.push(
  "Generated by `scripts/extract/crosscheck.ts` — do not edit by hand.",
  "",
  "- **Walkthrough** = *Dark Cloud 2 Walkthrough* v1.20 (Sky Render, 2007).",
  "- **FAQ** = *Dark Cloud 2 Weapon FAQ* v3.1 (JungleJim, 2016).",
  "",
  "Unless a line says otherwise, the app uses the **FAQ** for weapon data (newer, and it states it fixed base stats) and the **walkthrough** for everything else (checklists, sections, shops, inventions, Georama). Entries marked **kept:** say which value the app uses.",
);

// ---------- 1. coverage ----------
h("## 1. Weapon coverage");
const wtIds = new Set(wt.map((w) => w.id));
bullet(`FAQ lists ${faq.weapons.length} weapons, the walkthrough ${wt.length}.`);
for (const w of faq.weapons.filter((w) => !wtIds.has(w.id)))
  bullet(`In the FAQ only: **${w.name}** (the walkthrough spells it "Athena's Armet").`);
for (const w of wt.filter((w) => !byId.has(w.id)))
  bullet(
    `In the walkthrough only: **${w.name}**${w.name === "Wrench" ? " — the intro wrench that can't be obtained, so it is not in the app." : " — misspelling of the FAQ's Athena's Armlet."}`,
  );

// ---------- 2. weapon data ----------
h("## 2. Weapon data");
const order = ["at", "du", "fl", "ch", "li", "cy", "sm", "ex", "be", "sc"] as const;
const label: Record<string, string> = {
  at: "Attack",
  du: "Durability",
  fl: "Flame",
  ch: "Chill",
  li: "Lightning",
  cy: "Cyclone",
  sm: "Smash",
  ex: "Exorcism",
  be: "Beast",
  sc: "Scale",
};
const rows: string[] = [];
for (const w of wt) {
  const f = byId.get(w.id);
  if (!f) continue;
  if (w.baseAbs !== f.baseAbs)
    rows.push(`| ${f.name} | base ABS | ${w.baseAbs} | ${f.baseAbs} | FAQ |`);
  if (w.sp !== f.spPerLevel)
    rows.push(`| ${f.name} | SP per level | ${w.sp} | ${f.spPerLevel} | FAQ |`);
  if (w.combos !== undefined && f.combo && String(w.combos) !== f.combo.replace(/\D/g, ""))
    rows.push(`| ${f.name} | combo hits | ${w.combos} | ${f.combo} | FAQ |`);
  const mine = [f.maxStats.at, f.maxDu, ...order.slice(2).map((k) => f.maxStats[k])];
  order.forEach((k, i) => {
    if (w.maxStats[i] !== mine[i]) {
      const swapped = f.id === "angel-shooter" || f.id === "mobius-bangle";
      rows.push(
        `| ${f.name} | max ${label[k]} | ${w.maxStats[i]} | ${mine[i]} | ${swapped ? "walkthrough" : "FAQ"} |`,
      );
    }
  });
  const fa = new Set(f.abilities.map((a) => a.replace("-", " ")));
  const wa = new Set(w.abilities.map((a) => a.toLowerCase()));
  for (const a of fa)
    if (!wa.has(a))
      rows.push(
        `| ${f.name} | ability | (none) | ${a} | FAQ (it lists abilities gained by building up too) |`,
      );
  for (const a of wa) if (!fa.has(a)) rows.push(`| ${f.name} | ability | ${a} | (none) | FAQ |`);
  const fb = f.buildsUpTo.map(nameOf);
  const matched = new Set<string>();
  for (const t of w.buildsUpTo) {
    const hit = fb.find((x) => distance(norm(x), norm(t)) <= 2);
    if (hit) {
      matched.add(hit);
      if (hit !== t)
        rows.push(`| ${f.name} | build-up target spelling | ${t} | ${hit} | FAQ spelling |`);
    } else rows.push(`| ${f.name} | build-up target | ${t} | (not listed) | FAQ |`);
  }
  for (const x of fb)
    if (!matched.has(x)) rows.push(`| ${f.name} | build-up target | (not listed) | ${x} | FAQ |`);
  if (JSON.stringify([...w.enemies].sort()) !== JSON.stringify([...f.requiresKills].sort()))
    rows.push(
      `| ${f.name} | kill requirement | ${w.enemies.join(", ")} | ${f.requiresKills.join(", ")} | FAQ |`,
    );
}
out.push(
  "| Weapon | Field | Walkthrough | FAQ | Kept |",
  "| --- | --- | --- | --- | --- |",
  ...rows,
);
out.push("", "Notes:", "");
bullet(
  "Angel Shooter and Mobius Bangle: the two guides have the elemental maximums of the two weapons swapped. Only the walkthrough's version is consistent with Angel Shooter's base Cyclone (170), so the app takes these two rows from the walkthrough.",
);
bullet(
  "Abilities: the FAQ lists abilities a weapon gains on building up to it, the walkthrough only its native ones — so FAQ is a superset by design.",
);

// ---------- 3. minimum stats ----------
h('## 3. Walkthrough "Min. Stats" vs the build-up requirement computed from the FAQ');
out.push(
  "The walkthrough's *Min. Stats* are the minimum stats the previous weapon needs before it can build up to this one. The FAQ gives base stats; the requirement is `base − floor(10% of base)` per stat (FAQ section 4.5). Attack and the eight element stats compared (the walkthrough's second column, apparently durability, is ignored).",
  "",
);
const minRows: string[] = [];
const keys = ["at", "fl", "ch", "li", "cy", "sm", "ex", "be", "sc"] as const;
let minChecked = 0;
for (const w of wt) {
  const f = byId.get(w.id);
  if (!f || w.minStats.length < 10) continue;
  minChecked++;
  const walk = [w.minStats[0], ...w.minStats.slice(2)];
  const calc = keys.map((k) => f.baseStats[k] - Math.floor(0.1 * f.baseStats[k]));
  const bad = keys
    .map((k, i) => (walk[i] !== calc[i] ? `${label[k]} ${walk[i]} vs ${calc[i]}` : ""))
    .filter(Boolean);
  if (bad.length) minRows.push(`| ${f.name} | ${bad.join("; ")} |`);
}
bullet(`${minChecked} weapons compared; ${minRows.length} differ in at least one stat.`);
out.push(
  "",
  "Many of these look like column shifts in the walkthrough's table (the values are right but sit one stat to the side, e.g. Smash Wrench: Flame 0 / Chill 9 / Lightning 0 / Cyclone 18 / Smash 0 instead of Flame 18 / Chill 0 / Lightning 9 / Cyclone 0 / Smash 18). The app does not use these numbers; it computes requirements from the FAQ's base stats.",
);
if (minRows.length)
  out.push(
    "",
    "| Weapon | Differences (walkthrough vs computed from FAQ base) |",
    "| --- | --- |",
    ...minRows,
  );

// ---------- 4. shops ----------
h("## 4. Weapon shops (FAQ section 6.1 vs the walkthrough's shop lists)");
const wtShop = new Map<string, { shop: string; price?: number; chapter?: number }[]>();
for (const s of shops)
  for (const i of s.items) {
    const f = faq.weapons.find((w) => w.name === i.name);
    if (f)
      wtShop.set(f.id, [
        ...(wtShop.get(f.id) ?? []),
        { shop: s.name, price: i.price, chapter: i.chapter },
      ]);
  }
const shopRows: string[] = [];
const faqShop = new Map<string, { shop: string; price: number; chapter: number }[]>();
for (const s of faq.shops) faqShop.set(s.weaponId, [...(faqShop.get(s.weaponId) ?? []), s]);
const allShopWeapons = new Set([...wtShop.keys(), ...faqShop.keys()]);
for (const id of allShopWeapons) {
  const a = wtShop.get(id) ?? [];
  const b = faqShop.get(id) ?? [];
  const shopsOf = new Set([...a.map((x) => x.shop), ...b.map((x) => x.shop)]);
  for (const shop of shopsOf) {
    const x = a.find((s) => s.shop === shop);
    // FAQ lists the same weapon in every chapter; the first chapter it appears in is the one to compare.
    const ys = b.filter((s) => s.shop === shop).sort((p, q) => p.chapter - q.chapter);
    const y = ys[0];
    if (!x)
      shopRows.push(
        `| ${nameOf(id)} | ${shop} | not sold | ${y.price} gilda from ch. ${y.chapter} |`,
      );
    else if (!y)
      shopRows.push(
        `| ${nameOf(id)} | ${shop} | ${x.price} gilda${x.chapter ? ` from ch. ${x.chapter}` : ""} | not sold |`,
      );
    else {
      const parts: string[] = [];
      if (x.price !== y.price) parts.push(`price ${x.price} vs ${y.price}`);
      if ((x.chapter ?? 1) !== y.chapter)
        parts.push(`first chapter ${x.chapter ?? 1} vs ${y.chapter}`);
      if (parts.length)
        shopRows.push(
          `| ${nameOf(id)} | ${shop} | ${x.price} / ch. ${x.chapter ?? 1} | ${y.price} / ch. ${y.chapter} |`,
        );
    }
  }
}
out.push(
  `${shopRows.length} differences. **Kept:** the FAQ's shop lists for weapons (they are per chapter), the walkthrough's for items.`,
  "",
  "Most rows are not real contradictions: the walkthrough gives a chapter only for stock that is added later *inside* a shop; an item without a chapter is sold whenever the shop exists. It does not say when the shop itself opens, which the FAQ's per-chapter lists reveal for weapon shops (Starlight Weapons from ch. 3, G-Weapons from ch. 5, Jurak Arms from ch. 2, …). For item shops (Conda's Goods, Rufio's Elements, Star Items, …) the opening chapter is stated in neither guide, so item availability by chapter is approximate.",
  "",
  "| Weapon | Shop | Walkthrough | FAQ |",
  "| --- | --- | --- | --- |",
  ...shopRows,
);

// ---------- 5. invented weapons ----------
h("## 5. Invented weapons (FAQ section 6.3 vs the walkthrough's inventing list)");
const invRows: string[] = [];
for (const inv of faq.invented) {
  const name = nameOf(inv.weaponId);
  const w = inventions.find((i) => norm(i.name) === norm(name));
  if (!w) {
    invRows.push(`| ${name} | not in the walkthrough's inventing list | |`);
    continue;
  }
  const a = inv.ideas
    .map((alts) => alts.join(" / "))
    .sort()
    .join(" + ");
  const b = w.ideas
    .map((i) => i.name)
    .sort()
    .join(" + ");
  const flat = new Set(inv.ideas.flat().map(norm));
  const ideasDiffer =
    !w.ideas.every((i) => flat.has(norm(i.name))) || inv.ideas.length !== w.ideas.length;
  const mats = (l: { name: string; qty: number }[]) =>
    l
      .map((m) => `${m.qty}× ${m.name}`)
      .sort()
      .join(", ");
  const matsDiffer = mats(inv.materials) !== mats(w.components);
  if (ideasDiffer) invRows.push(`| ${name} | ideas | FAQ: ${a}; walkthrough: ${b} |`);
  if (matsDiffer)
    invRows.push(
      `| ${name} | materials | FAQ: ${mats(inv.materials)}; walkthrough: ${mats(w.components)} |`,
    );
}
out.push(
  `${invRows.length} differences (the walkthrough's chapter and price for the same invention are not in the FAQ).`,
  "",
  "| Weapon | What | Details |",
  "| --- | --- | --- |",
  ...invRows,
);

// ---------- 6. Georama rewards ----------
h("## 6. Georama completion rewards vs FAQ event weapons");
for (const a of georama.areas) {
  const hit = faq.events.find((e) => a.reward && nameOf(e.weaponId) === a.reward);
  bullet(
    `${a.name}: walkthrough reward "${a.reward}" — ${hit ? "FAQ agrees" : a.reward && /Stone/.test(a.reward) ? "not a weapon (FAQ doesn't list it)" : "FAQ lists it differently or not at all"}.`,
  );
}

// ---------- 7. enemy chapters ----------
h(
  "## 7. Kill-requirement enemies: chapter according to the FAQ vs where the walkthrough's sections list them",
);
const enemyChapters = new Map<string, Set<string>>();
for (const s of sections)
  for (const e of s.enemies) {
    const k = e.name.replace(/\*$/, "");
    (enemyChapters.get(k) ?? enemyChapters.set(k, new Set()).get(k)!).add(s.chapterId);
  }
const enemyRows: string[] = [];
for (const e of faq.killEnemies) {
  const seen = [...(enemyChapters.get(e.name) ?? [])].sort();
  const faqCh = e.chapter ? `c${e.chapter}` : "(not stated)";
  if (!seen.length) enemyRows.push(`| ${e.name} | ${faqCh} | not in any section's enemy list |`);
  else if (e.chapter && !seen.includes(faqCh))
    enemyRows.push(`| ${e.name} | ${faqCh} | ${seen.join(", ")} |`);
}
out.push(
  `${enemyRows.length} of ${faq.killEnemies.length} enemies differ or are not listed. The planner uses the FAQ's chapter.`,
  "",
  "| Enemy | FAQ chapter | Walkthrough sections |",
  "| --- | --- | --- |",
  ...enemyRows,
);

// ---------- 8. names ----------
h("## 8. Spelling and naming variants (normalised by the extractors)");
for (const [a, b] of [
  ["Vaccuum", "Vacuum"],
  ["Peeping Pole (overview list) / Peeping Hole (photo list)", "Peeping Hole"],
  ["Sulphur-Colored Juice / Sulfur-Colored Juice", "Sulfur-Colored Juice"],
  ["Decorative Light / Decorative Lights", "Decorative Lights"],
  ["Dr. Jaming / Doctor Jaming", "Doctor Jaming"],
  ["Clawn Robo's Attack", "Clown Robo's Attack"],
  ["Spinning Ivanov / Spinning Ivanoff", "Spinning Ivanoff"],
  ["Athena's Armet (walkthrough)", "Athena's Armlet (FAQ)"],
  ["Sargatana, Tsikikage (walkthrough build-up lists)", "Sargatanas, Tsukikage"],
  ["Super Alloy Body / Super-Alloy Body", "Super-Alloy Body"],
  ["Machine Gun Arm IIV", "Machine Gun Arm IV"],
  ["Refridgerator Body", "Refrigerator Body"],
  ["Level Up Powder / Level-Up Powder", "Level-Up Powder"],
])
  bullet(`${a} → ${b}`);

// ---------- 9. agreement ----------
h("## 9. Where the two guides agree");
bullet(
  "Item synth values: every item both guides list has identical stat gains (verified by a test).",
);
bullet(
  "Base ABS, SP per level and kill requirements agree for every weapon in both lists (see section 2 for the exceptions).",
);
bullet(
  "Medal totals per chapter in the walkthrough's medal breakdown match the sections extracted from the walkthrough's own chapters (127 levels).",
);

writeFileSync("src/data/INCONSISTENCIES.md", out.join("\n") + "\n");
console.log(`wrote src/data/INCONSISTENCIES.md (${out.length} lines)`);
